pipeline {
    agent any
	environment {
		 DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
		 DOCKERHUB_REPOSITORY = credentials('https://hub.docker.com/repository/docker/carlosvanoni/tema-final1')
    }

    stages {
        stage ('Get Artifact from JFrog') {
            steps {
                rtDownload (
		    serverId: 'localjfrog',
		    spec: '''{
			  "files": [
			    {
			      'pattern": "calculator/calculator.jar',
			      'target": "job1/build/libs/calculator.jar'
			    }
			  ]
		    }'''
		)
            }
        }
        
        stage ('Docker Build Image and Deploy in DockerHub') {
            steps {
                sh 'packer build -var "dockerhub_username=carlosvanoni" -var "dockerhub_password=dockerhub" -var "dockerhub_repository=$DOCKERHUB_REPOSITORY" "job2/temafinal1.json"'
            }
        }
    }
}
