pipeline {
    agent any
	

    stages {
        stage ('Get Artifact from JFrog') {
            steps {
                rtDownload (
		    serverId: 'Artifactory',
		    spec: '''{
			  "files": [
			    {
			      "pattern": "calculator/calculator.jar",
			       "target": "job1/build/libs/calculator.jar"
			    }
			  ]
		    }'''
		)
            }
        }
        
        stage ('Docker Build Image and Deploy in DockerHub') {
            steps {
                sh 'packer build -var "dockerhub_username=carlosvanoni" -var "dockerhub_password=dockerhub" -var "dockerhub_repository=$DOCKERHUB_REPOSITORY" "temafinal1.json"'
            }
        }
    }
}
