pipeline {
	
    agent any
	
	environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub_credentials')
    }
	

    stages {
        stage ('Get Artifact') {
            steps {
                rtDownload (
		    serverId: 'Artifactory',
		    spec: '''{
			  "files": [
			    {
			      "pattern": "calculator-app/calculator.jar",
			       "target": "job1/build/libs/calculator.jar"
			    }
			  ]
		    }'''
		)
            }
        }
	    
        
        stage ('Build Image and Deploy in DockerHub') {
            steps {
 sh 'packer build  -var "dockerhub_repository=carlosvanoni/tema-final1" -var "dockerhub_username=$DOCKERHUB_CREDENTIALS_USR" -var "dockerhub_password=$DOCKERHUB_CREDENTIALS_PSW" "job2/packer.json"'
            }
        }
    }
}
