pipeline {

    agent any

    stages {
        

        stage('Get artifact from JFrog server') {
            steps {
                rtDownload (
                    serverId: "Artifactory",
                    spec: """{
                        "files": [
                            {
                                "pattern": "calculator-app/calculator.jar",
                                "target": "job1/build/libs/calculator.jar"
                            }
                        ]
                    }"""
                )
            }
        }
          stage('build info') {
            steps {
                rtPublishBuildInfo (
                    serverId: "Artifactory"
                    )
            }
        }

        stage('Packer build') {
            steps {
                sh 'packer build  -var "dockerhub_repository_name=tema-final1" -var "dockerhub_username=carlosvanoni" -var "dockerhub_user_password=dockerhub" "calculator/job2/packer.json "'
            }
        }
    }
}
